/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AdministrationNoteRequest { 
    /**
     * The administration's uuid.
     */
    administrationId: string;
    /**
     * The note related to miss administration.
     */
    note?: string;
    /**
     * Indicates whether the notes field is unread.
     */
    ptComponentNoteToRead: AdministrationNoteRequest.PtComponentNoteToReadEnum;
}
export namespace AdministrationNoteRequest {
    export type PtComponentNoteToReadEnum = 'TO_READ' | 'READ' | 'NOT_AVAILABLE';
    export const PtComponentNoteToReadEnum = {
        TOREAD: 'TO_READ' as PtComponentNoteToReadEnum,
        READ: 'READ' as PtComponentNoteToReadEnum,
        NOTAVAILABLE: 'NOT_AVAILABLE' as PtComponentNoteToReadEnum
    };
}
