/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AdministrationDetailsDto { 
    administrationId?: string;
    administrationRoute?: string;
    drugName?: string;
    measurementUnit?: string;
    notes?: string;
    order?: number;
    quantity?: number;
    state?: string;
}
