/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DiaryRequest { 
    /**
     * The request start time stamp.
     */
    beginTsForDiaryEvents: number;
    /**
     * The request end time stamp.
     */
    endTsForDiaryEvents: number;
    /**
     * The patient's uuid.
     */
    patientUuid: string;
}
