/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MissedAdministrationRequest {
  /**
   * The note related to miss administration.
   */
  note: string;
  /**
   * Pt Component read note status
   */
  ptComponentNoteRead: MissedAdministrationRequest.PtComponentNoteReadEnum;
}
export namespace MissedAdministrationRequest {
  export type PtComponentNoteReadEnum = 'TO_READ' | 'READ' | 'NOT_AVAILABLE';
  export const PtComponentNoteReadEnum = {
    TOREAD: 'TO_READ' as PtComponentNoteReadEnum,
    READ: 'READ' as PtComponentNoteReadEnum,
    NOTAVAILABLE: 'NOT_AVAILABLE' as PtComponentNoteReadEnum
  };
}
