/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssistitoRequest } from './assistitoRequest';
import { DiagnosiRequest } from './diagnosiRequest';
import { PartecipanteRequest } from './partecipanteRequest';
import { SpecialistaRequest } from './specialistaRequest';


export interface CreateTeleconsultoRequest { 
    /**
     * Assistito
     */
    assistito?: AssistitoRequest;
    /**
     * Data (yyyy-MM-dd)
     */
    data: string;
    /**
     * Campo descrizione
     */
    descrizione: string;
    /**
     * ID durata
     */
    idDurata: string;
    /**
     * Campo note
     */
    note?: string;
    /**
     * Ora (hh:mm a)
     */
    ora: string;
    /**
     * Partecipanti del teleconsulto
     */
    partecipanti: Array<PartecipanteRequest>;
    /**
     * Quesiti diagnostici
     */
    quesitiDiagnostici?: Array<DiagnosiRequest>;
    /**
     * Specialista
     */
    specialista: SpecialistaRequest;
}
