/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ZoomMeeting } from './zoomMeeting';


export interface EventoInCorsoResponse { 
    /**
     * Data televisita (timestamp in secondi)
     */
    data?: number;
    /**
     * Durata (in minuti)
     */
    durata?: number;
    /**
     * Tipo di evento
     */
    tipo?: EventoInCorsoResponse.TipoEnum;
    /**
     * Zoom meeting
     */
    zoomMeeting?: ZoomMeeting;
}
export namespace EventoInCorsoResponse {
    export type TipoEnum = 'televisita' | 'teleconsulto';
    export const TipoEnum = {
        Televisita: 'televisita' as TipoEnum,
        Teleconsulto: 'teleconsulto' as TipoEnum
    };
}
