/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TeleconsultoDurataResponse } from './teleconsultoDurataResponse';
import { TeleconsultoPartecipanteResponse } from './teleconsultoPartecipanteResponse';
import { TeleconsultoSpecialistaResponse } from './teleconsultoSpecialistaResponse';


export interface TeleconsultoRicevutoSpecialistaResponse { 
    /**
     * Data (yyyy-MM-dd)
     */
    data?: string;
    /**
     * Campo descrizione
     */
    descrizione?: string;
    /**
     * Durata
     */
    durata?: TeleconsultoDurataResponse;
    /**
     * ID teleconsulto
     */
    id?: string;
    /**
     * Campo note
     */
    note?: string;
    /**
     * Ora (hh:mm a)
     */
    ora?: string;
    /**
     * Partecipanti del teleconsulto
     */
    partecipanti?: Array<TeleconsultoPartecipanteResponse>;
    /**
     * Richiedente
     */
    richiedente?: TeleconsultoSpecialistaResponse;
    /**
     * Stato
     */
    stato?: TeleconsultoRicevutoSpecialistaResponse.StatoEnum;
}
export namespace TeleconsultoRicevutoSpecialistaResponse {
    export type StatoEnum = 'PRESENTATO' | 'ACCETTATO' | 'IN_CORSO' | 'INTERROTTO' | 'SCADUTO' | 'EFFETTUATO';
    export const StatoEnum = {
        PRESENTATO: 'PRESENTATO' as StatoEnum,
        ACCETTATO: 'ACCETTATO' as StatoEnum,
        INCORSO: 'IN_CORSO' as StatoEnum,
        INTERROTTO: 'INTERROTTO' as StatoEnum,
        SCADUTO: 'SCADUTO' as StatoEnum,
        EFFETTUATO: 'EFFETTUATO' as StatoEnum
    };
}
