/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UpdateTelevisitaStatoResponse { 
    /**
     * ID televisita
     */
    id?: string;
    /**
     * Stato
     */
    stato?: UpdateTelevisitaStatoResponse.StatoEnum;
}
export namespace UpdateTelevisitaStatoResponse {
    export type StatoEnum = 'PRESENTATA' | 'RITIRATA' | 'RESPINTA' | 'PRESA_IN_CARICO' | 'RIFIUTATA' | 'ACCETTATA' | 'SCADUTA' | 'IN_CORSO' | 'EFFETTUATA' | 'INTERROTTA';
    export const StatoEnum = {
        PRESENTATA: 'PRESENTATA' as StatoEnum,
        RITIRATA: 'RITIRATA' as StatoEnum,
        RESPINTA: 'RESPINTA' as StatoEnum,
        PRESAINCARICO: 'PRESA_IN_CARICO' as StatoEnum,
        RIFIUTATA: 'RIFIUTATA' as StatoEnum,
        ACCETTATA: 'ACCETTATA' as StatoEnum,
        SCADUTA: 'SCADUTA' as StatoEnum,
        INCORSO: 'IN_CORSO' as StatoEnum,
        EFFETTUATA: 'EFFETTUATA' as StatoEnum,
        INTERROTTA: 'INTERROTTA' as StatoEnum
    };
}
