/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TeleconsultoAssistitoResponse } from './teleconsultoAssistitoResponse';
import { TeleconsultoDiagnosiResponse } from './teleconsultoDiagnosiResponse';
import { TeleconsultoDurataResponse } from './teleconsultoDurataResponse';
import { TeleconsultoPartecipanteResponse } from './teleconsultoPartecipanteResponse';


export interface UpdateTeleconsultoResponse { 
    /**
     * Assistito
     */
    assistito?: TeleconsultoAssistitoResponse;
    /**
     * Data (yyyy-MM-dd)
     */
    data?: string;
    /**
     * Durata
     */
    durata?: TeleconsultoDurataResponse;
    /**
     * Campo note
     */
    note?: string;
    /**
     * Ora (hh:mm a)
     */
    ora?: string;
    /**
     * Partecipanti del teleconsulto
     */
    partecipanti?: Array<TeleconsultoPartecipanteResponse>;
    /**
     * Quesiti diagnostici
     */
    quesitiDiagnostici?: Array<TeleconsultoDiagnosiResponse>;
    /**
     * Stato
     */
    stato?: UpdateTeleconsultoResponse.StatoEnum;
}
export namespace UpdateTeleconsultoResponse {
    export type StatoEnum = 'PRESENTATO' | 'IN_CORSO' | 'INTERROTTO' | 'SCADUTO' | 'EFFETTUATO';
    export const StatoEnum = {
        PRESENTATO: 'PRESENTATO' as StatoEnum,
        INCORSO: 'IN_CORSO' as StatoEnum,
        INTERROTTO: 'INTERROTTO' as StatoEnum,
        SCADUTO: 'SCADUTO' as StatoEnum,
        EFFETTUATO: 'EFFETTUATO' as StatoEnum
    };
}
