import { Province } from '../../pid/models/acceptance';

export const PROVINCE: Province[] = [
  { codice: 'AG', nome: 'Agrigento' },
  { codice: 'AL', nome: 'Alessandria' },
  { codice: 'AN', nome: 'Ancona' },
  { codice: 'AO', nome: 'Aosta' },
  { codice: 'AP', nome: 'Ascoli Piceno' },
  { codice: 'AQ', nome: 'L\'Aquila' },
  { codice: 'AR', nome: 'Arezzo' },
  { codice: 'AT', nome: 'Asti' },
  { codice: 'AV', nome: 'Avellino' },
  { codice: 'BA', nome: 'Bari' },
  { codice: 'BG', nome: 'Bergamo' },
  { codice: 'BI', nome: 'Biella' },
  { codice: 'BL', nome: 'Belluno' },
  { codice: 'BN', nome: 'Benevento' },
  { codice: 'BO', nome: 'Bologna' },
  { codice: 'BR', nome: 'Brindisi' },
  { codice: 'BS', nome: 'Brescia' },
  { codice: 'BT', nome: 'Barletta-Andria-Trani' },
  { codice: 'BZ', nome: 'Bolzano' },
  { codice: 'CA', nome: 'Cagliari' },
  { codice: 'CB', nome: 'Campobasso' },
  { codice: 'CE', nome: 'Caserta' },
  { codice: 'CH', nome: 'Chieti' },
  { codice: 'CL', nome: 'Caltanissetta' },
  { codice: 'CN', nome: 'Cuneo' },
  { codice: 'CO', nome: 'Como' },
  { codice: 'CR', nome: 'Cremona' },
  { codice: 'CS', nome: 'Cosenza' },
  { codice: 'CT', nome: 'Catania' },
  { codice: 'CZ', nome: 'Catanzaro' },
  { codice: 'EN', nome: 'Enna' },
  { codice: 'FC', nome: 'Forlì-Cesena' },
  { codice: 'FE', nome: 'Ferrara' },
  { codice: 'FG', nome: 'Foggia' },
  { codice: 'FI', nome: 'Firenze' },
  { codice: 'FM', nome: 'Fermo' },
  { codice: 'FR', nome: 'Frosinone' },
  { codice: 'GE', nome: 'Genova' },
  { codice: 'GO', nome: 'Gorizia' },
  { codice: 'GR', nome: 'Grosseto' },
  { codice: 'IM', nome: 'Imperia' },
  { codice: 'IS', nome: 'Isernia' },
  { codice: 'KR', nome: 'Crotone' },
  { codice: 'LC', nome: 'Lecco' },
  { codice: 'LE', nome: 'Lecce' },
  { codice: 'LI', nome: 'Livorno' },
  { codice: 'LO', nome: 'Lodi' },
  { codice: 'LT', nome: 'Latina' },
  { codice: 'LU', nome: 'Lucca' },
  { codice: 'MB', nome: 'Monza e della Brianza' },
  { codice: 'MC', nome: 'Macerata' },
  { codice: 'ME', nome: 'Messina' },
  { codice: 'MI', nome: 'Milano' },
  { codice: 'MN', nome: 'Mantova' },
  { codice: 'MO', nome: 'Modena' },
  { codice: 'MS', nome: 'Massa-Carrara' },
  { codice: 'MT', nome: 'Matera' },
  { codice: 'NA', nome: 'Napoli' },
  { codice: 'NO', nome: 'Novara' },
  { codice: 'NU', nome: 'Nuoro' },
  { codice: 'OR', nome: 'Oristano' },
  { codice: 'PA', nome: 'Palermo' },
  { codice: 'PC', nome: 'Piacenza' },
  { codice: 'PD', nome: 'Padova' },
  { codice: 'PE', nome: 'Pescara' },
  { codice: 'PG', nome: 'Perugia' },
  { codice: 'PI', nome: 'Pisa' },
  { codice: 'PN', nome: 'Pordenone' },
  { codice: 'PO', nome: 'Prato' },
  { codice: 'PR', nome: 'Parma' },
  { codice: 'PT', nome: 'Pistoia' },
  { codice: 'PU', nome: 'Pesaro e Urbino' },
  { codice: 'PV', nome: 'Pavia' },
  { codice: 'PZ', nome: 'Potenza' },
  { codice: 'RA', nome: 'Ravenna' },
  { codice: 'RC', nome: 'Reggio Calabria' },
  { codice: 'RE', nome: 'Reggio Emilia' },
  { codice: 'RG', nome: 'Ragusa' },
  { codice: 'RI', nome: 'Rieti' },
  { codice: 'RM', nome: 'Roma' },
  { codice: 'RN', nome: 'Rimini' },
  { codice: 'RO', nome: 'Rovigo' },
  { codice: 'SA', nome: 'Salerno' },
  { codice: 'SI', nome: 'Siena' },
  { codice: 'SO', nome: 'Sondrio' },
  { codice: 'SP', nome: 'La Spezia' },
  { codice: 'SR', nome: 'Siracusa' },
  { codice: 'SS', nome: 'Sassari' },
  { codice: 'SU', nome: 'Sud Sardegna' },
  { codice: 'SV', nome: 'Savona' },
  { codice: 'TA', nome: 'Taranto' },
  { codice: 'TE', nome: 'Teramo' },
  { codice: 'TN', nome: 'Trento' },
  { codice: 'TO', nome: 'Torino' },
  { codice: 'TP', nome: 'Trapani' },
  { codice: 'TR', nome: 'Terni' },
  { codice: 'TS', nome: 'Trieste' },
  { codice: 'TV', nome: 'Treviso' },
  { codice: 'UD', nome: 'Udine' },
  { codice: 'VA', nome: 'Varese' },
  { codice: 'VB', nome: 'Verbano-Cusio-Ossola' },
  { codice: 'VC', nome: 'Vercelli' },
  { codice: 'VE', nome: 'Venezia' },
  { codice: 'VI', nome: 'Vicenza' },
  { codice: 'VR', nome: 'Verona' },
  { codice: 'VS', nome: 'Medio Campidano' },
  { codice: 'VT', nome: 'Viterbo' },
  { codice: 'VV', nome: 'Vibo Valentia' },
  { codice: 'EE', nome: 'Estero' }
];
