// tslint:disable:quotemark
export const STATI = [{ nome: "Albania", codice: 0 },
{ nome: "Andorra", codice: 1 },
{ nome: "Armenia", codice: 2 },
{ nome: "Austria", codice: 3 },
{ nome: "Azerbaigian", codice: 4 },
{ nome: "Belgio", codice: 5 },
{ nome: "Bosnia -Erzegovina", codice: 6 },
{ nome: "Bulgaria", codice: 7 },
{ nome: "Cipro", codice: 8 },
{ nome: "Croazia", codice: 9 },
{ nome: "Danimarca", codice: 10 },
{ nome: "Estonia", codice: 11 },
{ nome: "Ex - Repubblica jugoslava di Macedonia", codice: 12 },
{ nome: "Finlandia", codice: 13 },
{ nome: "Francia", codice: 14 },
{ nome: "Georgia", codice: 15 },
{ nome: "Germania", codice: 16 },
{ nome: "Grecia", codice: 17 },
{ nome: "Irlanda", codice: 18 },
{ nome: "Islanda", codice: 19 },
{ nome: "Italia", codice: 20 },
{ nome: "Lettonia", codice: 21 },
{ nome: "Liechtenstein", codice: 22 },
{ nome: "Lituania", codice: 23 },
{ nome: "Lussemburgo", codice: 24 },
{ nome: "Malta", codice: 25 },
{ nome: "Moldavia", codice: 26 },
{ nome: "Monaco", codice: 27 },
{ nome: "Montenegro", codice: 28 },
{ nome: "Norvegia", codice: 29 },
{ nome: "Paesi Bassi", codice: 30 },
{ nome: "Polonia", codice: 31 },
{ nome: "Portogallo", codice: 32 },
{ nome: "Regno Unito", codice: 33 },
{ nome: "Repubblica Ceca", codice: 34 },
{ nome: "Romania", codice: 35 },
{ nome: "Federazione Russa", codice: 36 },
{ nome: "Serbia", codice: 37 },
{ nome: "Slovacchia", codice: 38 },
{ nome: "Slovenia", codice: 39 },
{ nome: "Spagna", codice: 40 },
{ nome: "Svezia", codice: 41 },
{ nome: "Svizzera", codice: 42 },
{ nome: "Turchia", codice: 43 },
{ nome: "Ucraina", codice: 44 },
{ nome: "Ungheria", codice: 45 }];
