/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ControllerErrorResponse } from '../model/controllerErrorResponse';
import { FindAllContattoByAssistitoResponse } from '../model/findAllContattoByAssistitoResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ContattoControllerService {

    protected basePath = 'http://127.0.0.1:8081';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Servizio #2 | Ritorna l’elenco dei contatti dell’assistito filtrato rispetto ai caratteri ricercati.
     * 
     * @param idAssistito ID assistito
     * @param nomeCognome Filtro nome/cognome
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllAssistitiUsingGET1(idAssistito: string, nomeCognome: string, observe?: 'body', reportProgress?: boolean): Observable<FindAllContattoByAssistitoResponse>;
    public getAllAssistitiUsingGET1(idAssistito: string, nomeCognome: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<FindAllContattoByAssistitoResponse>>;
    public getAllAssistitiUsingGET1(idAssistito: string, nomeCognome: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<FindAllContattoByAssistitoResponse>>;
    public getAllAssistitiUsingGET1(idAssistito: string, nomeCognome: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idAssistito === null || idAssistito === undefined) {
            throw new Error('Required parameter idAssistito was null or undefined when calling getAllAssistitiUsingGET1.');
        }

        if (nomeCognome === null || nomeCognome === undefined) {
            throw new Error('Required parameter nomeCognome was null or undefined when calling getAllAssistitiUsingGET1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idAssistito !== undefined && idAssistito !== null) {
            queryParameters = queryParameters.set('idAssistito', <any>idAssistito);
        }
        if (nomeCognome !== undefined && nomeCognome !== null) {
            queryParameters = queryParameters.set('nomeCognome', <any>nomeCognome);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<FindAllContattoByAssistitoResponse>(`${this.basePath}/contatti/get-by-assistito`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
